name: Update Sitemaps

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-sitemaps:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate dates
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: npm install --no-package-lock --no-save fast-glob
        
    - name: Generate sitemaps
      run: node .github/scripts/generate-sitemaps.js
      
    - name: Commit and push if sitemaps changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add all changes, including new and untracked files
        git add --all
        
        # Check if there are changes
        if git diff --staged --quiet; then
          echo "No sitemap changes to commit"
        else
          git commit -m "Auto-update sitemaps [skip ci]"
          git push
        fi